from core import PzServer
print()
print()
pz = PzServer(token="54d88903cb7efde2d9e82064a0ba02738cfcd5d4", host="pz-dev")
print(pz)
print()
print("DISPLAY PRODUCT TYPES")
pz.display_product_types()
print()
print()
print()
print("DISPLAY USERS")
pz.display_users()
print()
print()
print("DISPLAY RELEASES")
pz.display_releases()
print()
print()
print()
print()
metadata_specz_catalog = pz.get_product_metadata("6_true_redshifts") 
print(metadata_specz_catalog)
print()
print()
print()
print()
print()
#specz_catalog = pz_server.get_product(<product id number or name>)
specz_catalog = pz.get_product(6)
print(specz_catalog)
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
