channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.4.3
  - aiohttp=3.10.10
  - aiosignal=1.3.1
  - annotated-types=0.7.0
  - astropy=6.0.1
  - astropy-healpix=1.0.3
  - astropy-iers-data=0.2024.11.4.0.33.34
  - asttokens=2.4.1
  - attrs=24.2.0
  - aws-c-auth=0.8.0
  - aws-c-cal=0.8.0
  - aws-c-common=0.10.0
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.0
  - aws-c-io=0.15.0
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.0
  - aws-c-sdkutils=0.2.0
  - aws-checksums=0.2.0
  - aws-crt-cpp=0.29.1
  - aws-sdk-cpp=1.11.407
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - bleach=6.2.0
  - blosc=1.21.6
  - bokeh=3.5.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.32.3
  - ca-certificates=2024.8.30
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cartopy=0.24.0
  - cdshealpix=0.7.0
  - certifi=2024.8.30
  - cffi=1.17.1
  - cfitsio=4.4.1
  - cftime=1.6.4
  - charset-normalizer=3.4.0
  - click=8.1.7
  - cloudpickle=3.1.0
  - colorama=0.4.6
  - colorcet=3.1.0
  - comm=0.2.2
  - contourpy=1.3.0
  - cramjam=2.8.4rc3
  - cycler=0.12.1
  - cytoolz=1.0.0
  - dask=2024.10.0
  - dask-core=2024.10.0
  - dask-expr=1.1.16
  - dask-jobqueue=0.9.0
  - datashader=0.16.3
  - debugpy=1.8.8
  - decorator=5.1.1
  - deprecated=1.2.14
  - distributed=2024.10.0
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - fastparquet=2024.5.0
  - firefox=132.0.2
  - fonttools=4.54.1
  - freetype=2.12.1
  - freexl=2.0.0
  - frozenlist=1.5.0
  - fsspec=2024.10.0
  - geckodriver=0.35.0
  - geopandas-base=1.0.1
  - geos=3.13.0
  - geotiff=1.7.3
  - geoviews=1.13.0
  - geoviews-core=1.13.0
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.7.1
  - h11=0.14.0
  - h2=4.1.0
  - h5py=3.12.1
  - hats=0.4.3
  - hats-import=0.4.1
  - hdf4=4.2.15
  - hdf5=1.14.3
  - healpy=1.18.0
  - holoviews=1.20.0
  - hpack=4.0.0
  - hpgeom=1.4.0
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - importlib_metadata=8.5.0
  - ipykernel=6.29.5
  - ipython=8.29.0
  - ipywidgets=8.1.5
  - jedi=0.19.1
  - jinja2=3.1.4
  - jproperties=2.1.2
  - json-c=0.18
  - jupyter_bokeh=4.0.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyterlab_widgets=3.0.13
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.3
  - libarchive=3.7.4
  - libarrow=18.0.0
  - libarrow-acero=18.0.0
  - libarrow-dataset=18.0.0
  - libarrow-substrait=18.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.10.1
  - libdeflate=1.22
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgdal-core=3.9.3
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - libgoogle-cloud=2.30.0
  - libgoogle-cloud-storage=2.30.0
  - libgrpc=1.67.1
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnetcdf=4.9.2
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libopenblas=0.3.28
  - libparquet=18.0.0
  - libpng=1.6.44
  - libprotobuf=5.28.2
  - libre2-11=2024.07.02
  - librttopo=1.1.0
  - libsodium=1.0.20
  - libspatialite=5.1.0
  - libsqlite=3.47.0
  - libssh2=1.11.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.13.4
  - libzip=1.11.2
  - libzlib=1.3.1
  - linkify-it-py=2.0.3
  - llvmlite=0.43.0
  - locket=1.0.0
  - lsdb=0.4.2
  - lsst-sphgeom=27.2024.4400
  - lz4=4.3.3
  - lz4-c=1.9.4
  - lzo=2.10
  - markdown=3.6
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.7
  - mdit-py-plugins=0.4.2
  - mdurl=0.1.2
  - minizip=4.0.7
  - mocpy=0.17.0
  - msgpack-python=1.1.0
  - multidict=6.1.0
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nested-dask=0.3.0
  - nested-pandas=0.3.1
  - netcdf4=1.7.1
  - networkx=3.4.2
  - numba=0.60.0
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openssl=3.4.0
  - orc=2.0.2
  - outcome=1.3.0.post0
  - packaging=24.1
  - pandas=2.2.3
  - panel=1.5.3
  - param=2.1.1
  - parso=0.8.4
  - partd=1.4.2
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.0.0
  - pip=24.3.1
  - platformdirs=4.3.6
  - proj=9.5.0
  - prompt-toolkit=3.0.48
  - propcache=0.2.0
  - psutil=6.1.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=18.0.0
  - pyarrow-core=18.0.0
  - pycparser=2.22
  - pyct=0.5.0
  - pydantic=2.9.2
  - pydantic-core=2.23.4
  - pyerfa=2.0.1.4
  - pygments=2.18.0
  - pyogrio=0.10.0
  - pyparsing=3.2.0
  - pyproj=3.7.0
  - pyshp=2.3.1
  - pysocks=1.7.1
  - python=3.12.7
  - python-dateutil=2.9.0
  - python-tzdata=2024.2
  - python_abi=3.12
  - pytz=2024.1
  - pyviz_comms=3.0.3
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - re2=2024.07.02
  - readline=8.2
  - regions=0.10
  - requests=2.32.3
  - s2n=1.5.6
  - scipy=1.14.1
  - selenium=4.27.1
  - selenium-manager=4.27.0
  - setuptools=75.3.0
  - shapely=2.0.6
  - six=1.16.0
  - snappy=1.2.1
  - sniffio=1.3.1
  - sortedcontainers=2.4.0
  - sqlite=3.47.0
  - stack_data=0.6.2
  - tables-io=0.9.10
  - tblib=3.0.0
  - tk=8.6.13
  - toolz=1.0.0
  - tornado=6.4.1
  - tqdm=4.67.0
  - traitlets=5.14.3
  - trio=0.27.0
  - trio-websocket=0.11.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - uc-micro-py=1.0.3
  - unicodedata2=15.1.0
  - universal_pathlib=0.2.5
  - uriparser=0.9.8
  - urllib3=2.2.3
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.44.0
  - widgetsnbextension=4.0.13
  - wrapt=1.16.0
  - wsproto=1.2.0
  - xarray=2024.10.0
  - xerces-c=3.2.5
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - xyzservices=2024.9.0
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.16.0
  - zeromq=4.3.5
  - zict=3.0.0
  - zipp=3.20.2
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
