name: Rubin latest compatibility

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 45 7 * * *

jobs:
  rubin-latest-compatibility:
    name: rubin_latest_compatibility
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    - name: Install dependencies with Rubin latest constraints
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e '.[dev]' -c constraints-rubin-latest.txt
    - name: Run unit tests with pytest
      run: |
        python -m pytest
